config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :poems do
    get "index"
    get "new"
    post "create"
    get "show"
    get "my_poems", :on => :collection
    post "cycle_nouns"
    post "shuffle_nouns"
    post "cycle_adjectives"
    post "shuffle_adjectives"
    post "cycle_lines"
    post "shuffle_lines"
    post "toggle_public"
    get "about", :on => :collection
    get "delete"
  end

  get "random_poem", :to => "random_poems#random_poem"

  root 'poems#index'
end

app/models/poem.rb
class Poem < ApplicationRecord
end

app/controllers/poems_controller.rb
require 'rubygems'

class PoemsController < ApplicationController
  def index
    @poems = Poem.where(:user_id => nil).or(Poem.where(:public => true)).order(:updated_at => :desc)
  end

  def my_poems
    @poems = Poem.where(:user_id => current_user&.id).order(:updated_at => :desc)
  end

  def new
    @poem = Poem.new(params.permit(:title, :text))
  end

  def create
    @poem = Poem.new(params.require(:poem).permit(:title, :text).merge(:user_id => current_user&.id))
    @poem.update(:original => @poem.text)

    @poem.save
    redirect_to @poem
  end

  def show
    @poem = Poem.find(params[:id])
  end

  def delete
    @poem = Poem.find(params[:poem_id])
    @poem.destroy

    redirect_to poems_path
  end

  def toggle_public
    @poem = Poem.find(params[:poem_id])
    @poem.update(:public => !@poem.public)

    @poem.save
    redirect_to @poem
  end

  def cycle_nouns
    @poem = Poem.find(params[:poem_id])

    if @poem.text.presence
      @poem.update(:text => PoemsHelper.cycle_nouns_in_text(@poem.text))
    end

    redirect_to @poem
  end

  def shuffle_nouns
    @poem = Poem.find(params[:poem_id])

    if @poem.text.presence
      @poem.update(:text => PoemsHelper.shuffle_nouns_in_text(@poem.text))
    end

    redirect_to @poem
  end

  def cycle_adjectives
    @poem = Poem.find(params[:poem_id])

    if @poem.text.presence
      @poem.update(:text => PoemsHelper.cycle_adjectives_in_text(@poem.text))
    end

    redirect_to @poem
  end

  def shuffle_adjectives
    @poem = Poem.find(params[:poem_id])

    if @poem.text.presence
      @poem.update(:text => PoemsHelper.shuffle_adjectives_in_text(@poem.text))
    end

    redirect_to @poem
  end

  def cycle_lines
    @poem = Poem.find(params[:poem_id])

    if @poem.text.presence
      @poem.update(:text => PoemsHelper.cycle_lines_in_text(@poem.text))
    end

    redirect_to @poem
  end

  def shuffle_lines
    @poem = Poem.find(params[:poem_id])

    if @poem.text.presence
      @poem.update(:text => PoemsHelper.shuffle_lines_in_text(@poem.text))
    end

    redirect_to @poem
  end
end

app/helpers/poems_helper.rb
require 'engtagger'

module PoemsHelper
  PLACEHOLDER = "XXXXXX".freeze
  NOUN_LIST = ["NN", "NNP", "NNS", "NNPS"].freeze
  ADJECTIVE_LIST = ["JJ", "JJR", "JJS"].freeze

  def self.cycle_adjectives_in_text(text)
    adjectives_in_order = self.get_adjectives_in_order(text)
    with_placeholders = self.replace_words_with_placeholders(text, adjectives_in_order)
    cycled_adjectives = self.cycle_array(adjectives_in_order)
    text = self.replace_placeholders_with_words(with_placeholders, cycled_adjectives)

    self.fix_articles(text)
  end

  def self.shuffle_adjectives_in_text(text)
    adjectives_in_order = self.get_adjectives_in_order(text)
    with_placeholders = self.replace_words_with_placeholders(text, adjectives_in_order)
    shuffled_adjectives = self.shuffle_array(adjectives_in_order)
    text = self.replace_placeholders_with_words(with_placeholders, shuffled_adjectives)

    self.fix_articles(text)
  end

  def self.cycle_nouns_in_text(text)
    nouns_in_order = self.get_nouns_in_order(text)
    with_placeholders = self.replace_words_with_placeholders(text, nouns_in_order)
    cycled_nouns = self.cycle_array(nouns_in_order)
    text = self.replace_placeholders_with_words(with_placeholders, cycled_nouns)

    self.fix_articles(text)
  end

  def self.shuffle_nouns_in_text(text)
    nouns_in_order = self.get_nouns_in_order(text)
    with_placeholders = self.replace_words_with_placeholders(text, nouns_in_order)
    shuffled_nouns = self.shuffle_array(nouns_in_order)
    text = self.replace_placeholders_with_words(with_placeholders, shuffled_nouns)

    self.fix_articles(text)
  end

  def self.cycle_lines_in_text(text)
    text = text.gsub("\r\n\r\n", "\r\n \r\n") # Preserve empty lines
    split_by_lines = text.split("\r\n")
    cycled_lines = cycle_array(split_by_lines)
    cycled_lines.join("\r\n").concat("\r\n")
  end

  def self.shuffle_lines_in_text(text)
    text = text.gsub("\r\n\r\n", "\r\n \r\n") # Preserve empty lines
    split_by_lines = text.split("\r\n")
    shuffled_lines = shuffle_array(split_by_lines)
    shuffled_lines.join("\r\n").concat("\r\n")
  end

  def self.fix_articles(text)
    articles_in_order = self.get_articles_in_order(text)
    with_placeholders = self.replace_words_with_placeholders(text, articles_in_order)
    correct_articles = self.get_correct_articles(text)
    text = self.replace_placeholders_with_words(with_placeholders, correct_articles)
  end

  def self.cycle_array(nouns)
    nouns.rotate(-1)
  end

  def self.shuffle_array(nouns)
    nouns.shuffle
  end

  def self.replace_placeholders_with_words(text, nouns)
    nouns.each do |noun|
      text = text.sub(PLACEHOLDER, noun)
    end
    text
  end

  def self.replace_words_with_placeholders(text, nouns)
    nouns.each do |noun|
      text = text.sub(/\b#{noun}\b/, "#{PLACEHOLDER}")
    end
    text
  end

  def self.get_nouns_in_order(raw_text)
    tgr = EngTagger.new
    tagged = tgr.add_tags(raw_text)
    nouns = []
    tokens = tagged.split(" ")

    tokens.each do |token|
      if self.is_noun?(token)
        noun = ActionView::Base.full_sanitizer.sanitize(token)

        #if the last character is puncutation, remove it
        if ["—", ".", "-", ";"].any? { |char| noun[-1] == char }
          noun = noun[0...-1]
        end

        if self.is_alpha?(noun)
          nouns << noun
        end
      end
    end
    nouns
  end

  def self.get_adjectives_in_order(raw_text)
    tgr = EngTagger.new
    tagged = tgr.add_tags(raw_text)
    adjectives = []
    tokens = tagged.split(" ")

    tokens.each do |token|
      if self.is_adjective?(token)
        adjective = ActionView::Base.full_sanitizer.sanitize(token)

        #if the last character is puncutation, remove it
        if ["—", ".", "-", ";"].any? { |char| adjective[-1] == char }
          adjective = adjective[0...-1]
        end

        if self.is_alpha?(adjective)
          adjectives << adjective
        end
      end
    end
    adjectives
  end

  def self.get_adjectives(string)
    tgr = EngTagger.new
    tagged = tgr.add_tags(string)
    tgr.get_adjectives(tagged)
  end

  def self.get_articles_in_order(string)
    words = string.split(/\W+/)

    words.select { |word| ["A", "An", "a", "an"].include?(word) }
  end

  def self.get_correct_articles(string)
    words = string.split(/\W+/)

    words.each_with_index.map do |word, index|
      if ["A", "An"].include?(word)
        if "aeiouAEIOU".chars.include?(words[index + 1][0])
          "An"
        else
          "A"
        end
      elsif ["a", "an"].include?(word)
        if "aeiouAEIOU".chars.include?(words[index + 1][0])
          "an"
        else
          "a"
        end
      end
    end.compact
  end

  def self.is_noun?(token)
    token.match?(/<nn>.*<\/nn>/) || token.match?(/<nnp>.*<\/nnp>/) || token.match?(/<nnps>.*<\/nnps>/) || token.match?(/<nns>.*<\/nns>/)
  end

  def self.is_adjective?(token)
    token.match?(/<jj>.*<\/jj>/) || token.match?(/<jjr>.*<\/jjr>/) || token.match?(/<jjs>.*<\/jjs>/)
  end

  def self.is_alpha?(string)
    string.match?(/^[[:alpha:]]+$/)
  end
end

app/views/poems/about.html.erb
<h1 class="center my-3">About</h1>

<div class="purple-background-light" style="margin-left:20%; margin-right:20%; padding:20px; margin-top:20px; border-radius: 25px;">
  <p>This project was inspired by an undergraduate poetry workshop I took with Zoë Brigley Thompson at Ohio State.</p>
  <p>The exercise was to take a pre-existing poem (yours or someone else's) and replace each noun with the noun that appear 7 positions after it in the dictionary. Alternatively, one could cycle the nouns within the poem 7 spots.</p>
  <p>The prompt was to then take a line from the mutated poem and write a poem based on it. The writer could then remove the original line or keep it.</p>
  <br>
  <p>Zoë's exercise was inspired by the OuLiPo movement, which you can read about <a href="https://www.poetryfoundation.org/learn/glossary-terms/oulipo">here</a>.</p>
  <br>
  <p>Create a poem and try cycling or shuffling the nouns, adjectives and lines.</p>
  <p>Or go to Random Poem and generate a poem from lines of randomly selected poems.</p>
  <br>
  <p>Create an account or log in to create your own OuLiPo poems!</p>
</div>

app/views/poems/index.html.erb
<h1 class="center my-3">Public poems</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col" style="width: 10%"></th>
      <th scope="col" style="width: 20%">Title</th>
      <th scope="col" style="width: 70%">Text</th>
    </tr>
  </thead>

  <tbody>
    <% @poems.each do |poem| %>
      <tr>
        <td></td>
        <td><%= poem.title %></td>
        <td class="poem">
          <%= simple_format(poem.text).html_safe %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/poems/my_poems.erb
<h1 class="center my-3">My poems</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col" style="width: 10%"></th>
      <th scope="col" style="width: 20%">Title</th>
      <th scope="col">Text</th>
      <th scope="col"></th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @poems.each do |poem| %>
      <tr>
        <td></td>
        <td><%= poem.title %></td>
        <td class="poem">
          <%= simple_format(poem.text).html_safe %>
        </td>
        <% if poem.public %>
          <td class="purple">Public</td>
        <% else %>
          <td class="purple">Public</td>
        <% end %>
        <td><%= link_to 'Show', poem_path(poem) %></td>
        <td class="padding-sides"><%= link_to 'Delete', poem_delete_path(poem) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/poems/new.html.erb
<div class="margin-10" style="margin-left:20%; margin-right:20%;">
  <h1>New poem</h1>
  <%= form_for @poem do |form| %>
    <div >
      <p>
        <%= form.label :title %><br>
        <%= form.text_field :title, :class => "form-control" %>
      </p>

      <p>
        <%= form.label :text %><br>
        <%= form.text_area :text, :class => "form-control" %>
      </p>

      <p>
        <%= form.submit "Continue", :class => "btn btn-outline-secondary" %>
      </p>
    </div>
  <% end %>
</div>

app/views/poems/show.html.erb
<div class="margin-10">

  <div class="container ml-0">
    <div class="row">
      <div class="col-6">
        <h3><%= @poem.title %></h3>
        <%= simple_format(@poem.text).html_safe %>
      </div>
      <div id="originalPoem" style="display: none;" class="col-6">
        <h3><%= @poem.title %></h3>
        <%= simple_format(@poem.original).html_safe %>
      </div>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <td>
          <div class="margin-vertical">
            <%= form_tag poem_cycle_nouns_path(@poem.id), method: :post do %>
              <%= submit_tag 'Cycle nouns', :class => "btn btn-outline-secondary" %>
            <% end %>
          </div>
        </td>
        <td>

          <div class="margin-vertical">
            <%= form_tag poem_shuffle_nouns_path(@poem.id), method: :post  do %>
              <%= submit_tag 'Shuffle nouns', :class => "btn btn-outline-secondary" %>
            <% end %>
          </div>
        </td>
      </tr>
      <tr>
        <td>
          <div class="margin-vertical">
            <%= form_tag poem_cycle_adjectives_path(@poem.id), method: :post do %>
              <%= submit_tag 'Cycle adjectives', :class => "btn btn-outline-secondary" %>
            <% end %>
          </div>
        </td>
        <td>
          <div class="margin-vertical">
            <%= form_tag poem_shuffle_adjectives_path(@poem.id), method: :post  do %>
              <%= submit_tag 'Shuffle adjectives', :class => "btn btn-outline-secondary" %>
            <% end %>
          </div>
        </td>
      </tr>
      <tr>
        <td>
          <div class="margin-vertical">
            <%= form_tag poem_cycle_lines_path(@poem.id), method: :post  do %>
              <%= submit_tag 'Cycle lines', :class => "btn btn-outline-secondary" %>
            <% end %>
          </div>
        </td>
        <td>
          <div class="margin-vertical">
            <%= form_tag poem_shuffle_lines_path(@poem.id), method: :post  do %>
              <%= submit_tag 'Shuffle lines', :class => "btn btn-outline-secondary" %>
            <% end %>
          </div>
        </td>
      </tr>
    </tbody>
      <tr>
        <td>
          <div class="margin-vertical">
            <button onclick="showHideOriginalPoem()" class="btn btn-outline-secondary btn-orange" id="showOriginalPoem">Show Original</button>
          </div>
        </td>
      </tr>
      <tr>
        <td>
          <div class="margin-vertical">
            <%= form_tag poem_toggle_public_path(@poem.id), method: :post  do %>
              <% if @poem.public %>
                <%= submit_tag 'Make private', :class => "btn btn-outline-secondary btn-blue" %>
              <% else %>
                <%= submit_tag 'Make public', :class => "btn btn-outline-secondary btn-blue" %>
              <% end %>
            <% end %>
          </div>
        </td>
      </tr>
  </table>
</div>