config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :poems do
    get "index"
    get "new"
    post "create"
    get "show"
    get "my_poems", :on => :collection
    post "cycle_nouns"
    post "shuffle_nouns"
    post "cycle_adjectives"
    post "shuffle_adjectives"
    post "cycle_lines"
    post "shuffle_lines"
    post "toggle_public"
    get "about", :on => :collection
    get "delete"
  end

  get "random_poem", :to => "random_poems#random_poem"

  root 'poems#index'
end

app/controllers/random_poems_controller.rb
class RandomPoemsController < ApplicationController
  def random_poem
    if params[:generate]
      @text = RandomPoemHelper.random_poem
    end
  end
end

app/helpers/random_poem_helper.rb
require 'nokogiri'
require 'open-uri'

module RandomPoemHelper
  def self.random_poem
    poem = ""
    10.times do
      line = self.random_line
      poem << line << "\n" if line.length < 100
    end
    poem
  end

  def self.random_line
    poem_array = random_poem_as_array
    random_line_from_array(poem_array)
  end

  def self.random_line_from_array(line_array)
    line_array.shuffle.first
  end

  def self.random_poem_as_array
    url = 'https://www.poetryoutloud.org/poems-and-performance/random-poem'

    html = open(url)
    poem_text = _get_poem_text_from_html(html)

    return [""] if poem_text.nil?

    poem_text.split(/\R+/)
  end

  private

  def self._get_poem_text_from_html(html)
    doc = Nokogiri::HTML(html)

    poem = doc&.at_css('.bodyTxt_1')
    poem_paragraph = poem&.at_css('p')
    poem_paragraph&.xpath('text()')&.text
  end
end

app/views/random_poems/random_poem.html.erb
<div class="width-40 padding-top-30" style="margin: auto;">
  <h1 class="center my-3">Random Poem Generation</h1>

  <div class="purple-background-light" style="padding:20px; margin-top:20px; margin-bottom:20px; border-radius: 25px;">
    <p>This tool retrieves up to 10 random poems from the internet, and then selects a random line from each poem. The lines are combined to create a new poem, displayed here.</p>
    <p>This may take several seconds, due to the time required to find poems.</p>
  </div>

  <div class="center">
    <%= link_to('Random Poem', random_poem_path(:generate => true), method: :get, :class => "btn btn-outline-secondary text-center") %>
  </div>

  <div class="margin-top-30">
    <%= simple_format(@text).html_safe %>
  </div>

  <% unless @text.nil? %>
    <div class="margin-vertical">
      <%= link_to('Save Poem', new_poem_path(:text => @text), method: :get, :class => "btn btn-outline-secondary") %>
    </div>
  <% end %>
</div>