config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :poems do
    get "index"
    get "new"
    post "create"
    get "show"
    get "my_poems", :on => :collection
    post "cycle_nouns"
    post "shuffle_nouns"
    post "cycle_adjectives"
    post "shuffle_adjectives"
    post "cycle_lines"
    post "shuffle_lines"
    post "toggle_public"
    get "about", :on => :collection
    get "delete"
  end

  get "random_poem", :to => "random_poems#random_poem"

  root 'poems#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="alert-danger custom-error">
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<br>

<%- if controller_name != 'sessions' %>
  <div class="margin-top-10">
    <%= link_to "Log in", new_session_path(resource_name) %><br />
  </div>
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <div class="margin-top-10">
    <%= link_to "Sign up", new_registration_path(resource_name) %><br />
  </div>
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <div class="margin-top-10">
    <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
  </div>
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <div class="margin-top-10">
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
  </div>
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <div class="margin-top-10">
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
  </div>
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <div class="margin-top-10">
      <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
    </div>
  <% end %>
<% end %>